################################################################################
##                                                                            ##
## Plot the accuracy of transcript abundance estimates (for simulated data)   ##
## and the correlation between the abundance estimates for different methods  ##
##                                                                            ##
## Inputs:                                                                    ##
## * scorerds: list containing abundance estimates and characteristics for    ##
##             junctions, transcripts and genes, as well as gene scores.      ##
##             Generated by calculate_gene_scores.R                           ##
## * quantmethods: string containing the quantification methods to consider,  ##
##                 separated by commas (no spaces)                            ##
## * truthrda: the file generated by polyester, containing true transcript    ##
##             abundances (or '' if not a simulated data set)                 ##
## * truthmodgenesrds: vector with the names of the genes whose transcripts   ##
##                     have been altered (or '' if not a simulated data set)  ##
## * outrds: output rds file. The name will be used to determine the name of  ##
##           the output figures.                                              ##
##                                                                            ##
## Outputs:                                                                   ##
## * A png figure with a pairs plot showing the association between           ##
##   abundance estimates from different methods                               ##
## * A png figure showing the association between abundance estimates and     ##
##   true abundances                                                          ##
##                                                                            ##
################################################################################

args <- (commandArgs(trailingOnly = TRUE))
for (i in 1:length(args)) {
  eval(parse(text = args[[i]]))
}

quantmethods <- strsplit(quantmethods, ",")[[1]]

print(scorerds)
print(quantmethods)
print(truthrda)
print(truthmodgenesrds)
print(outrds)

suppressPackageStartupMessages({
  library(dplyr)
  library(tidyr)
  library(ggplot2)
  library(cowplot)
  library(GGally)
})

source("Rscripts/helper_plot_functions.R")

## Define helper functions for pairs plots
sqrt_diagonal <- function(data, mapping, ...) {
  ggally_densityDiag(data, mapping, ...) + scale_x_sqrt()
}
sqrt_points <- function(data, mapping, ...) {
  ggally_points(data, mapping, alpha = 0.25, size = 0.25, ...) + 
    scale_x_sqrt() + scale_y_sqrt()
}

## Read transcript abundance estimates
estimates <- readRDS(scorerds)$transcripts %>% 
  dplyr::select(transcript, gene, count, method) %>%
  dplyr::filter(method %in% quantmethods)

## Pairs plots
png(gsub("\\.rds$", "_transcripts_pairs.png", outrds), width = 12, height = 12,
    unit = "in", res = 300)
toplot <- estimates %>% dplyr::select(-gene) %>% 
  tidyr::spread(method, count) %>% dplyr::select(-transcript)
print(ggpairs(toplot, 
              lower = list(continuous = sqrt_points),
              upper = list(continuous = combinecor),
              diag = list(continuous = sqrt_diagonal)) + 
        theme_bw())
dev.off()

png(gsub("\\.rds$", "_genes_pairs.png", outrds), width = 12, height = 12,
    unit = "in", res = 300)
toplot <- estimates %>% dplyr::select(-transcript) %>% 
  dplyr::group_by(gene, method) %>% dplyr::summarize(count = sum(count)) %>% 
  dplyr::ungroup() %>% tidyr::spread(method, count) %>% dplyr::select(-gene)
print(ggpairs(toplot, 
              lower = list(continuous = sqrt_points),
              upper = list(continuous = combinecor),
              diag = list(continuous = sqrt_diagonal)) + 
        theme_bw())
dev.off()

if (truthrda != '' && truthmodgenesrds != '') {
  ## Read true (simulated) abundance estimates
  load(truthrda)  ## counts_matrix
  truth <- as.data.frame(counts_matrix) %>% dplyr::select(sample_01) %>%
    tibble::rownames_to_column("transcript") %>% dplyr::rename(truth = sample_01)
  
  ## Merge
  merged <- estimates %>% tidyr::spread(method, count) %>% 
    dplyr::full_join(truth, by = c("transcript")) %>%
    replace(., is.na(.), 0) %>%
    tidyr::gather(method, count, -transcript, -gene, -truth)
  
  ## Add gene annotation for modified transcripts
  idx <- grep("utrfrom", merged$transcript)
  for (i in idx) {
    merged$gene[i] <- merged$gene[match(strsplit(merged$transcript[i], "_")[[1]][1], 
                                        merged$transcript)]
  }
  
  ## Add label for genes whose transcripts are modified
  truthmodgenes <- readRDS(truthmodgenesrds)
  merged <- merged %>% dplyr::mutate(modified_gene = gene %in% truthmodgenes)
  
  ## Plot estimated vs true counts
  ## Transcripts
  corrs <- merged %>% dplyr::group_by(method) %>% 
    dplyr::summarize(pearson = signif(cor(truth, count, method = "pearson", 
                                          use = "pairwise.complete.obs"), 3),
                     spearman = signif(cor(truth, count, method = "spearman", 
                                           use = "pairwise.complete.obs"), 3))
  png(gsub("\\.rds$", "_transcripts.png", outrds), width = 12, height = 12, 
      unit = "in", res = 300)
  print(ggplot(merged, aes(x = truth, y = count)) + 
          geom_abline(slope = 1, intercept = 0) + ggtitle("Transcript") + 
          geom_point(alpha = 0.3, size = 0.5, aes(color = modified_gene)) + theme_bw() + 
          geom_label(data = corrs, x = -Inf, y = Inf, hjust = -0.05, vjust = 1.1, 
                     aes(label = paste0("Pearson: ", pearson, "\nSpearman: ", spearman))) + 
          facet_wrap(~ method) + xlab("True count") + ylab("Estimated count") + 
          scale_x_sqrt() + scale_y_sqrt())
  dev.off()
  
  ## Genes
  mergedgene <- merged %>% dplyr::group_by(method, gene) %>% 
    dplyr::summarize(truth = sum(truth), count = sum(count),
                     modified_gene = unique(modified_gene))
  corrsgene <- mergedgene %>% dplyr::group_by(method) %>% 
    dplyr::summarize(pearson = signif(cor(truth, count, method = "pearson", 
                                          use = "pairwise.complete.obs"), 3),
                     spearman = signif(cor(truth, count, method = "spearman", 
                                           use = "pairwise.complete.obs"), 3))
  png(gsub("\\.rds$", "_genes.png", outrds), width = 12, height = 12, 
      unit = "in", res = 300)
  print(ggplot(mergedgene, 
               aes(x = truth, y = count)) + 
          geom_abline(slope = 1, intercept = 0) + ggtitle("Gene") + 
          geom_point(alpha = 0.3, size = 0.5, aes(color = modified_gene)) + theme_bw() + 
          geom_label(data = corrsgene, x = -Inf, y = Inf, hjust = -0.05, vjust = 1.1, 
                     aes(label = paste0("Pearson: ", pearson, "\nSpearman: ", spearman))) + 
          facet_wrap(~ method) + xlab("True count") + ylab("Estimated count") + 
          scale_x_sqrt() + scale_y_sqrt())
  dev.off()
  
  ## Pairs plot
  png(gsub("\\.rds$", "_transcripts_pairs_withmod.png", outrds), width = 12, height = 12,
      unit = "in", res = 300)
  toplot <- merged %>% dplyr::select(-gene, -truth) %>% 
    tidyr::spread(method, count) %>% dplyr::select(-transcript) %>%
    dplyr::mutate(modified_gene = as.factor(modified_gene))
  print(ggpairs(toplot, 
                columns = which(colnames(toplot) != "modified_gene"), 
                mapping = ggplot2::aes(colour = modified_gene),
                lower = list(continuous = sqrt_points),
                diag = list(continuous = sqrt_diagonal)) + 
          theme_bw())
  dev.off()
  
}

saveRDS(NULL, file = outrds)
date()
sessionInfo()

