################################################################################
##                                                                            ##
## Plot performance for simulated data                                        ##
##                                                                            ##
## Inputs:                                                                    ##
## * scorerds: list containing abundance estimates and characteristics for    ##
##             junctions, transcripts and genes, as well as gene scores.      ##
##             Generated by calculate_gene_scores.R                           ##
## * truthrda: the file generated by polyester, containing true transcript    ##
##             abundances (or '' if not a simulated data set)                 ##
## * truthmodgenesrds: vector with the names of the genes whose transcripts   ##
##                     have been altered (or '' if not a simulated data set)  ##
## * gtf: gtf file, to get 3'UTR lengths                                      ##
## * uniqjuncreadsthreshold: the total number of uniquely mapping junction    ##
##                           reads (in a gene), only genes with more than     ##
##                           this number will be used for the comparison      ##
## * outrds: output file                                                      ##
##                                                                            ##
## Outputs:                                                                   ##
## * png figures illustrating the relative contribution of each type of       ##
##   transcript (contributing UTR, contributing internal structure, other)    ##
##   to the count and TPM of a gene                                           ##
##                                                                            ##
################################################################################

args <- (commandArgs(trailingOnly = TRUE))
for (i in 1:length(args)) {
  eval(parse(text = args[[i]]))
}

print(scorerds)
print(truthrda)
print(gtf)
print(uniqjuncreadsthreshold)
print(outrds)

suppressPackageStartupMessages({
  library(rtracklayer)
  library(dplyr)
  library(tidyr)
  library(ggplot2)
})

scores <- readRDS(scorerds)
load(truthrda)
modgenes <- readRDS(truthmodgenesrds)
gtf <- rtracklayer::import(gtf, format = "gtf")

transcripts <- scores$transcripts

## Get the coordinates and lengths of the 3'UTR for each transcript
utrs <- as.data.frame(gtf) %>% dplyr::filter(type == "three_prime_utr") %>%
  dplyr::group_by(transcript_id) %>%
  dplyr::summarize(start = min(start), end = max(end), width = sum(width), 
                   seqnames = seqnames[1], gene_id = gene_id[1], strand = strand[1])

## Set up data frame with information about modified transcripts
modtrans <- data.frame(
  mod_transcript = grep("utrfrom", rownames(counts_matrix), value = TRUE), 
  stringsAsFactors = FALSE) %>%
  tidyr::separate(mod_transcript, into = c("internal_tx", "utr_tx"), sep = "_utrfrom_") %>%
  dplyr::mutate(internal_tx_utrlength = utrs$width[match(internal_tx, utrs$transcript_id)],
                utr_tx_utrlength = utrs$width[match(utr_tx, utrs$transcript_id)]) %>%
  dplyr::mutate(gene = transcripts$gene[match(internal_tx, transcripts$transcript)]) %>%
  dplyr::mutate(utr_selected = ifelse(internal_tx_utrlength > utr_tx_utrlength, "short", "long"))

## Subset transcript abundance table to only the transcripts in the modified genes
gene_summary <- transcripts %>% 
  dplyr::filter(gene %in% modgenes) %>%
  dplyr::mutate(tr_type = ifelse(transcript %in% modtrans$internal_tx, 
                                 "Contributing internal structure", 
                                 ifelse(transcript %in% modtrans$utr_tx, 
                                        "Contributing 3'UTR", "Other"))) %>%
  dplyr::left_join(modtrans %>% dplyr::select(gene, utr_selected)) %>%
  dplyr::select(gene, count, TPM, tr_type, utr_selected, method) %>%
  dplyr::group_by(gene, utr_selected, tr_type, method) %>% 
  dplyr::summarize(count = sum(count), TPM = sum(TPM)) %>% dplyr::ungroup() %>%
  dplyr::group_by(gene, method) %>% dplyr::mutate(count = count/sum(count),
                                                  TPM = TPM/sum(TPM)) %>%
  dplyr::ungroup()

## Plot relative contributions to gene count/TPM from the different transcript
## categories
png(gsub("\\.rds$", "_count.png", outrds), width = 7, height = 7, unit = "in", res = 300)
print(ggplot(gene_summary, aes(x = utr_selected, y = count, color = tr_type)) + 
        geom_boxplot(outlier.size = 0.3) + facet_wrap(~ method) + 
        theme_bw() + scale_color_manual(values = c("#9900cc", "#009933", "#0099cc"),
                                        name = "Transcript class") + 
        xlab("Selected 3'UTR") + ylab("Relative contribution to gene count"))
dev.off()

png(gsub("\\.rds$", "_tpm.png", outrds), width = 7, height = 7, unit = "in", res = 300)
print(ggplot(gene_summary, aes(x = utr_selected, y = TPM, color = tr_type)) + 
        geom_boxplot(outlier.size = 0.3) + facet_wrap(~ method) + 
        theme_bw() + scale_color_manual(values = c("#9900cc", "#009933", "#0099cc"),
                                        name = "Transcript class") + 
        xlab("Selected 3'UTR") + ylab("Relative contribution to gene TPM"))
dev.off()

## Plot scores for modified and unmodified genes
genes <- scores$genes %>% 
  dplyr::mutate(geneclass = ifelse(gene %in% modgenes, "modified", "unmodified")) %>%
  dplyr::filter(uniqjuncreads > uniqjuncreadsthreshold)
png(gsub("\\.rds$", "_scores.png", outrds), width = 7, height = 7, unit = "in", res = 300)
print(ggplot(genes, aes(x = geneclass, y = score, color = geneclass)) + 
        geom_boxplot(outlier.size = 0.3) + 
        facet_wrap(~ method) + theme_bw() + 
        scale_color_manual(values = c(modified = "#9900cc", unmodified = "#009933"),
                           name = "Gene class") + 
        xlab(""))
dev.off()

date()
sessionInfo()
