################################################################################
##                                                                            ##
## Plot correlation between scores from different methods                     ##
##                                                                            ##
## Inputs:                                                                    ##
## * scorerds: list containing abundance estimates and characteristics for    ##
##             junctions, transcripts and genes, as well as gene scores.      ##
##             Generated by calculate_gene_scores.R                           ##
## * quantmethods: string containing the quantification methods to consider,  ##
##                 separated by commas (no spaces)                            ##
## * uniqjuncreadsthreshold: the total number of uniquely mapping junction    ##
##                           reads (in a gene), only genes with more than     ##
##                           this number will be used for the comparison      ##
## * outrds: output rds file. The name will be used to determine the name of  ##
##           the output figures.                                              ##
##                                                                            ##
## Outputs:                                                                   ##
## * A png figure with a pairs plot showing the association between the       ##
##   from each pair of methods.                                               ##
## * A png figure with a dendrogram illustrating the similarities between the ##
##   methods                                                                  ##
##                                                                            ##
################################################################################

args <- (commandArgs(trailingOnly = TRUE))
for (i in 1:length(args)) {
  eval(parse(text = args[[i]]))
}

quantmethods <- strsplit(quantmethods, ",")[[1]]

print(scorerds)
print(quantmethods)
print(uniqjuncreadsthreshold)
print(outrds)

suppressPackageStartupMessages({
  library(dplyr)
  library(ggplot2)
  library(cowplot)
  library(GGally)
})

source("Rscripts/helper_plot_functions.R")

## Read scores
scores <- readRDS(scorerds)$genes

## Filter
highexpression <- scores %>% dplyr::filter(uniqjuncreads >= uniqjuncreadsthreshold) %>% 
  dplyr::pull(gene)
scores_wide <- scores %>% dplyr::filter(method %in% quantmethods & 
                                          gene %in% highexpression) %>%
  dplyr::select(gene, method, score) %>% 
  tidyr::spread(method, score) %>% as.data.frame() %>% tibble::column_to_rownames("gene")

## Pairs plot
png(gsub("\\.rds$", "_pairs.png", outrds), width = 8, height = 8, 
    unit = "in", res = 300)
print(ggpairs(scores_wide,
              lower = list(continuous = wrap("points", alpha = 0.3, size = 0.25)),
              upper = list(continuous = combinecor)) + 
        theme_bw())
dev.off()

## Dendrogram
png(gsub("\\.rds$", "_clustering.png", outrds), width = 5, height = 5, 
    unit = "in", res = 300)
cormat <- cor(scores_wide, use = "pairwise.complete.obs")
distmat <- as.dist(sqrt(2*(1 - cormat)))
hcl <- hclust(distmat)
nodePar <- list(pch = c(NA, 19), col = "black")
plot(as.dendrogram(hcl), type = "rectangle", ylab = "Dissimilarity", nodePar = nodePar)
dev.off()

saveRDS(NULL, file = outrds)
date()
sessionInfo()
